name: Currency Fetcher

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update rates
        run: |
          wget http://api.exchangeratesapi.io/v1/latest?access_key=${{ secrets.EXCHANGE_RATES_API_KEY }} -O rates.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || (git add rates.json && git commit -m "chore: update rates")
          git push
